version: '3'

services:
  worker:
    build: worker
    restart: always
    depends_on:
      - mongo
      - rabbitmq
    links:
      - mongo
      - rabbitmq
  producer:
    build: producer
    restart: always
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    ports:
      - "8000:8000"
  mongo:
    image: mongo
    volumes:
      - dbdata:/data/db
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "8080:15672"
      - "5672:5672"
volumes:
  dbdata:
